[2022-03-17 19:48:01,084] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_project.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-03-17 19:48:01,095] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_project.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-03-17 19:48:01,095] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 19:48:01,095] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-17 19:48:01,095] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-17 19:48:01,106] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-03-17 19:48:01,112] {standard_task_runner.py:52} INFO - Started process 657 to run task
[2022-03-17 19:48:01,117] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag_project', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_project.py', '--cfg-path', '/tmp/tmpnbx7tng6', '--error-file', '/tmp/tmp480ggj54']
[2022-03-17 19:48:01,118] {standard_task_runner.py:77} INFO - Job 26: Subtask local_to_gcs_task
[2022-03-17 19:48:01,183] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag_project.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 06aea6ade097
[2022-03-17 19:48:01,224] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-17 19:48:01,246] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag_project
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-03-17 19:48:02,174] {python.py:175} INFO - Done. Returned value was: None
[2022-03-17 19:48:02,186] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag_project, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220317T194801, end_date=20220317T194802
[2022-03-17 19:48:02,212] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-17 19:48:02,246] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-03-20 06:18:43,905] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_project.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-03-20 06:18:43,916] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcs_dag_project.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [queued]>
[2022-03-20 06:18:43,916] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 06:18:43,916] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-03-20 06:18:43,916] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-03-20 06:18:43,930] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): local_to_gcs_task> on 2020-01-01 00:00:00+00:00
[2022-03-20 06:18:43,936] {standard_task_runner.py:52} INFO - Started process 411 to run task
[2022-03-20 06:18:43,941] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcs_dag_project', 'local_to_gcs_task', 'scheduled__2020-01-01T00:00:00+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_gcs_dag_project.py', '--cfg-path', '/tmp/tmpxwivf118', '--error-file', '/tmp/tmpwrnn3hz_']
[2022-03-20 06:18:43,942] {standard_task_runner.py:77} INFO - Job 45: Subtask local_to_gcs_task
[2022-03-20 06:18:44,008] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcs_dag_project.local_to_gcs_task scheduled__2020-01-01T00:00:00+00:00 [running]> on host 974079c1cd0d
[2022-03-20 06:18:44,074] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-03-20 06:18:44,107] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcs_dag_project
AIRFLOW_CTX_TASK_ID=local_to_gcs_task
AIRFLOW_CTX_EXECUTION_DATE=2020-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2020-01-01T00:00:00+00:00
[2022-03-20 06:18:45,192] {python.py:175} INFO - Done. Returned value was: None
[2022-03-20 06:18:45,204] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcs_dag_project, task_id=local_to_gcs_task, execution_date=20200101T000000, start_date=20220320T061843, end_date=20220320T061845
[2022-03-20 06:18:45,237] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-03-20 06:18:45,270] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
